### ISSUE TITLE
│OSError: Model file not found: adam/average_model.pt

### ISSUE THREAD

**Issue by wyzjack** [juntang-zhuang/fairseq-adabelief#1]
When I ran the code as your guide, I came across this error. Any help?
![image](https://user-images.githubusercontent.com/36599296/115898389-15a03980-a490-11eb-9756-4bf464ddc1e5.png)

**Comment by juntang-zhuang** [comment]
Could you post the full error log? The script first trains the model, then evaluates it with another python file. The error here says there's no saved weight, which is probably caused by the training failure so nothing is saved.

**Comment by wyzjack** [comment]
Thanks for the information. I have fixed the bug
